# Generated by Django 4.2 on 2023-05-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Canteen",
            fields=[
                (
                    "canteen_id",
                    models.CharField(
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                        verbose_name="食堂ID",
                    ),
                ),
                (
                    "canteen_name",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "中央食堂"), (2, "北部食堂"), (3, "吉田食堂"), (4, "ルネ")],
                        default=1,
                        verbose_name="食堂名",
                    ),
                ),
                (
                    "canteen_location",
                    models.CharField(max_length=64, verbose_name="食堂の場所"),
                ),
                ("canteen_url", models.URLField(verbose_name="食堂リンク")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_account",
                    models.CharField(max_length=16, unique=True, verbose_name="アカウント"),
                ),
                (
                    "user_name",
                    models.CharField(
                        default=models.CharField(
                            max_length=16, unique=True, verbose_name="アカウント"
                        ),
                        max_length=32,
                        verbose_name="名前",
                    ),
                ),
                (
                    "user_pwd",
                    models.CharField(
                        default="pwd", max_length=16, verbose_name="パスワード"
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="メール"
                    ),
                ),
                (
                    "age",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="年齢"
                    ),
                ),
                (
                    "height",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="身長"
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="体重"
                    ),
                ),
                (
                    "gender",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "男"), (2, "女"), (3, "その他")],
                        null=True,
                        verbose_name="性別",
                    ),
                ),
                ("create_time", models.DateTimeField(verbose_name="アカウント作成時間")),
                (
                    "allergen",
                    models.CharField(
                        blank=True, max_length=128, null=True, verbose_name="アレルゲン"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dish_url", models.URLField(verbose_name="料理のリンク")),
                (
                    "dish_name",
                    models.CharField(
                        default="Unknown", max_length=64, verbose_name="料理名"
                    ),
                ),
                (
                    "dish_en_name",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="英語の料理名"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="商品画像のリンク"),
                ),
                (
                    "price",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="組価(税込)"
                    ),
                ),
                (
                    "energy",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="エネルギー"
                    ),
                ),
                (
                    "protein",
                    models.FloatField(blank=True, null=True, verbose_name="タンパク質"),
                ),
                ("fat", models.FloatField(blank=True, null=True, verbose_name="脂質")),
                (
                    "carbohydrates",
                    models.FloatField(blank=True, null=True, verbose_name="炭水化物"),
                ),
                (
                    "salt",
                    models.FloatField(blank=True, null=True, verbose_name="食塩相当量"),
                ),
                (
                    "calcium",
                    models.IntegerField(blank=True, null=True, verbose_name="カルシウム"),
                ),
                ("veg", models.IntegerField(blank=True, null=True, verbose_name="野菜量")),
                ("iron", models.FloatField(blank=True, null=True, verbose_name="鉄")),
                (
                    "vitamin_a",
                    models.IntegerField(blank=True, null=True, verbose_name="ビタミン A"),
                ),
                (
                    "vitamin_b1",
                    models.FloatField(blank=True, null=True, verbose_name="ビタミン B1"),
                ),
                (
                    "vitamin_b2",
                    models.FloatField(blank=True, null=True, verbose_name="ビタミン B2"),
                ),
                (
                    "vitamin_c",
                    models.IntegerField(blank=True, null=True, verbose_name="ビタミン C"),
                ),
                (
                    "place_of_origin",
                    models.CharField(
                        blank=True, default="Unknown", max_length=64, verbose_name="原産地"
                    ),
                ),
                (
                    "allergies",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="アレルギー"
                    ),
                ),
                (
                    "canteen",
                    models.ForeignKey(
                        default=650111,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_recsys.canteen",
                        verbose_name="食堂ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(auto_now_add=True, verbose_name="注文日")),
                (
                    "dish",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_recsys.menu",
                        verbose_name="料理ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_recsys.user",
                        verbose_name="ユーザID",
                    ),
                ),
            ],
        ),
    ]
