# Generated by Django 4.2 on 2023-04-25 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User_security",
            fields=[
                (
                    "user_account",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("user_pwd", models.CharField(max_length=16)),
                ("user_email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="menu_recsys.user_security",
                    ),
                ),
                ("user_name", models.CharField(max_length=32)),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("sex", models.CharField(max_length=8)),
            ],
        ),
    ]
