# Generated by Django 4.2 on 2023-05-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_account', models.CharField(max_length=16, unique=True, verbose_name='アカウント')),
                ('user_name', models.CharField(max_length=32, verbose_name='名前')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メール')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='年齢')),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='身長')),
                ('weight', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='体重')),
                ('gender', models.PositiveSmallIntegerField(blank=True, choices=[(1, '男'), (2, '女'), (3, 'その他')], null=True, verbose_name='性別')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='アカウント作成時間')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
