# Generated by Django 4.2 on 2023-04-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_recsys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_email",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AddField(
            model_name="user",
            name="user_pwd",
            field=models.CharField(default="", max_length=16),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(default="Unknown", max_length=8),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_account",
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(
                default=models.CharField(
                    max_length=16, primary_key=True, serialize=False
                ),
                max_length=32,
                unique=True,
            ),
        ),
        migrations.DeleteModel(
            name="User_security",
        ),
    ]
