# Generated by Django 4.2 on 2023-05-03 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu_recsys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="canteen",
            field=models.ForeignKey(
                default="650111",
                on_delete=django.db.models.deletion.CASCADE,
                to="menu_recsys.canteen",
                verbose_name="食堂ID",
            ),
        ),
    ]
