# Generated by Django 4.2 on 2023-05-03 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu_recsys", "0002_alter_menu_canteen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history_order",
            name="dish",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="menu_recsys.menu",
                verbose_name="料理ID",
            ),
        ),
        migrations.AlterField(
            model_name="history_order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="menu_recsys.user",
                verbose_name="ユーザID",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="canteen",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="menu_recsys.canteen",
                verbose_name="食堂ID",
            ),
        ),
    ]
