# Generated by Django 4.2 on 2023-05-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_recsys', '0002_user_is_staff_alter_user_age_alter_user_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
