# Generated by Django 4.2 on 2023-04-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_recsys", "0002_user_user_email_user_user_pwd_alter_user_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="sex",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_email",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_pwd",
            field=models.CharField(default="pwd", max_length=16),
        ),
        migrations.AlterField(
            model_name="user",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
