# Generated by Django 4.2 on 2023-05-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "menu_recsys",
            "0003_alter_history_order_dish_alter_history_order_user_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="dish_en_name",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="英語の料理名"
            ),
        ),
    ]
