# Generated by Django 4.2 on 2023-04-25 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu_recsys", "0003_alter_user_height_alter_user_sex_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Canteen",
            fields=[
                (
                    "canteen_id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                ("canteen_name", models.CharField(max_length=32)),
                ("canteen_location", models.CharField(max_length=64)),
                ("canteen_url", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="user_name",
            field=models.CharField(
                default=models.CharField(
                    max_length=16, primary_key=True, serialize=False
                ),
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "dish_id",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
                (
                    "dish_name",
                    models.CharField(
                        default=models.CharField(
                            max_length=16, primary_key=True, serialize=False
                        ),
                        max_length=64,
                    ),
                ),
                (
                    "dish_en_name",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("price", models.IntegerField(blank=True, null=True)),
                ("energy", models.IntegerField(blank=True, null=True)),
                ("protein", models.IntegerField(blank=True, null=True)),
                ("fat", models.IntegerField(blank=True, null=True)),
                ("carbohydrates", models.IntegerField(blank=True, null=True)),
                ("salt", models.IntegerField(blank=True, null=True)),
                ("calcium", models.IntegerField(blank=True, null=True)),
                ("veg", models.IntegerField(blank=True, null=True)),
                ("iron", models.IntegerField(blank=True, null=True)),
                ("vitaminA", models.IntegerField(blank=True, null=True)),
                ("vitaminB1", models.IntegerField(blank=True, null=True)),
                ("vitaminB2", models.IntegerField(blank=True, null=True)),
                ("vitaminC", models.IntegerField(blank=True, null=True)),
                (
                    "place_of_origin",
                    models.CharField(blank=True, default="Unknown", max_length=64),
                ),
                ("dish_url", models.URLField()),
                (
                    "canteen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_recsys.canteen",
                    ),
                ),
            ],
        ),
    ]
