# Generated by Django 4.2 on 2023-04-25 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu_recsys", "0004_canteen_alter_user_user_name_menu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menu",
            old_name="canteen",
            new_name="canteen_id",
        ),
        migrations.CreateModel(
            name="History_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField()),
                (
                    "dish_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_recsys.menu",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="menu_recsys.user",
                    ),
                ),
            ],
        ),
    ]
