# Generated by Django 4.2 on 2023-05-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_recsys', '0004_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'ダイエット'), (2, '現状を維持する'), (3, '体重を増やしたい')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(3, '田佬')], null=True),
        ),
    ]
