# Generated by Django 4.2 on 2023-05-03 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_recsys", "0004_alter_menu_dish_en_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="dish_en_name",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="英語の料理名"
            ),
        ),
    ]
