# Generated by Django 4.2 on 2023-05-11 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_recsys', '0005_user_target_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergen',
            field=models.BooleanField(choices=[(1, '卵'), (2, '牛乳'), (3, '落花生'), (4, 'そば'), (5, '小麦'), (6, 'えび'), (7, 'かに'), (8, 'あわび'), (9, 'いか'), (10, 'いくら'), (11, 'さけ'), (12, 'さば'), (13, '牛肉'), (14, '鶏肉'), (15, '豚肉'), (16, '大豆'), (17, '松茸'), (18, '山芋'), (19, 'オレンジ'), (20, '桃'), (21, 'キウイフルーツ'), (22, 'りんご'), (23, 'くるみ'), (24, 'ゼラチン'), (25, 'バナナ'), (26, 'ゴマ'), (27, 'カシューナッツ')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '男'), (2, '女'), (3, 'その他')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='target',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 'ダイエット'), (5, '現状を維持する'), (6, '体重を増やしたい')], null=True),
        ),
    ]
