# Generated by Django 4.2 on 2023-05-02 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu_recsys", "0005_rename_canteen_menu_canteen_id_history_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="allergies",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="menu",
            name="dish_name",
            field=models.CharField(default="unknown", max_length=64),
        ),
    ]
