# Generated by Django 4.2 on 2023-05-11 05:18

from django.db import migrations
import multiselectfield.db.fields
import multiselectfield.validators


class Migration(migrations.Migration):

    dependencies = [
        ('menu_recsys', '0006_user_allergen_alter_user_gender_alter_user_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='allergen',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '卵'), (2, '牛乳'), (3, '落花生'), (4, 'そば'), (5, '小麦'), (6, 'えび'), (7, 'かに'), (8, 'あわび'), (9, 'いか'), (10, 'いくら'), (11, 'さけ'), (12, 'さば'), (13, '牛肉'), (14, '鶏肉'), (15, '豚肉'), (16, '大豆'), (17, '松茸'), (18, '山芋'), (19, 'オレンジ'), (20, '桃'), (21, 'キウイフルーツ'), (22, 'りんご'), (23, 'くるみ'), (24, 'ゼラチン'), (25, 'バナナ'), (26, 'ゴマ'), (27, 'カシューナッツ')], default='なし', max_length=71, validators=[multiselectfield.validators.MaxValueMultiFieldValidator(5)]),
        ),
    ]
