# Generated by Django 4.2 on 2023-05-11 06:15

from django.db import migrations, models
import multiselectfield.db.fields
import multiselectfield.validators


class Migration(migrations.Migration):

    dependencies = [
        ('menu_recsys', '0007_alter_user_allergen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='momentum',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '運動はほぼしない 生活の大部分が座位'), (2, '普通 座位中心、通勤・通学・家事での移動、軽いスポーツをしている'), (3, '活発 移動が多い、立ち仕事、運動習慣あり')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='allergen',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, '卵'), (2, '牛乳'), (3, '落花生'), (4, 'そば'), (5, '小麦'), (6, 'えび'), (7, 'かに'), (8, 'あわび'), (9, 'いか'), (10, 'いくら'), (11, 'さけ'), (12, 'さば'), (13, '牛肉'), (14, '鶏肉'), (15, '豚肉'), (16, '大豆'), (17, '松茸'), (18, '山芋'), (19, 'オレンジ'), (20, '桃'), (21, 'キウイフルーツ'), (22, 'りんご'), (23, 'くるみ'), (24, 'ゼラチン'), (25, 'バナナ'), (26, 'ゴマ'), (27, 'カシューナッツ')], max_length=71, validators=[multiselectfield.validators.MaxValueMultiFieldValidator(27)]),
        ),
    ]
